version: '{build}'
platform:
  - x64
image: Visual Studio 2017

before_build:
 - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
 - mkdir "%APPVEYOR_BUILD_FOLDER%\Build"
 - cd "%APPVEYOR_BUILD_FOLDER%\Build"
 - cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Release ..

build_script:
  - cd "%APPVEYOR_BUILD_FOLDER%\Build"
  - cmake --build .
after_build:
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - 7z a Alimer.7z "%APPVEYOR_BUILD_FOLDER%\Build\bin\Release"
test: off
artifacts:
  path: Alimer.7z

branches:
  only:
    - master

skip_commits:
  files:
    - .travis.yml