version: '{branch}-{build}'

shallow_clone: false

environment:
  matrix:
  - COMPILER: VS2017
    ARCHITECTURE: x86
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  - COMPILER: VS2017
    ARCHITECTURE: x64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  #- COMPILER: MINGW_W64_7_2
  #  ARCHITECTURE: x64
  #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

build:
  verbosity: detailed
  parallel: true

branches:
  only:
    - master

skip_commits:
  files:
    - .travis.yml

install:
  - mkdir c:\ninja && cd c:\ninja
  - appveyor-retry appveyor DownloadFile https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-win.zip
  - 7z x ninja-win.zip
  - set PATH=C:\ninja;%PATH%
  - ninja --version

before_build:
  - cmd: cd C:\projects\alimer
  - IF "%ARCHITECTURE%" == "x86" IF "%COMPILER%" == "VS2017"
    call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  - IF "%ARCHITECTURE%" == "x64" IF "%COMPILER%" == "VS2017"
    call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

build_script:
  - mkdir "%APPVEYOR_BUILD_FOLDER%\build"
  - cd "%APPVEYOR_BUILD_FOLDER%\build"
  - cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_SYSTEM_VERSION="10.0.17763.0" -DCMAKE_INSTALL_PREFIX="%APPVEYOR_BUILD_FOLDER%\alimer" ..
  - cmake --build . --target install

after_build:
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - 7z a alimer.7z "%APPVEYOR_BUILD_FOLDER%\alimer"

test: off
artifacts:
  path: alimer.7z
