language: cpp

notifications:
  email:
    on_success: never
    on_failure: never

branches:
  except:
    - /^(.*[^\w])?(appveyor|no-ci)-.+$/
    
matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      env:
        - GENERATOR="Unix Makefiles"
    - os: linux
      dist: trusty
      compiler: clang
      env:
        - GENERATOR="Unix Makefiles"
    - os: osx
      compiler: clang
      osx_image: xcode10
      env:
        - GENERATOR="Unix Makefiles"
    - os: windows
      env:
        - GENERATOR="Visual Studio 15 2017"
    - os: windows
      env:
        - GENERATOR="Visual Studio 15 2017 Win64"

script:
  - mkdir build
  - cd build
  - cmake -G "${GENERATOR}" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="Alimer-SDK" ..
  - cmake --build . --target install