language:
  - cpp

branches:
  except:
    - /^(.*[^\w])?(appveyor|no-ci)-.+$/

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: gcc
      before_install:
        - sudo apt-get install xorg-dev
      env:
        - GENERATOR="Unix Makefiles"
    - os: windows
      env:
        - GENERATOR="Visual Studio 15 2017 Win64"

before_script:

script:
  - mkdir build
  - cd build
  - cmake -G "${GENERATOR}" -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build . --config Release

notifications:
  email:
    on_success: never
    on_failure: never