dist: trusty  
language:
  - cpp

branches:
  except:
    - /^(.*[^\w])?(appveyor|no-ci)-.+$/

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-6
            - ninja-build
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - libopenal-dev
            - libasound2-dev
      env:
        - GENERATOR="Ninja"
        - CC=gcc-6
        - CXX=g++-6
    - os: windows
      env:
        - GENERATOR="Visual Studio 15 2017 Win64"

before_script:

script:
  - mkdir build
  - cd build
  - cmake -G "${GENERATOR}" -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build . --config Release

notifications:
  email:
    on_success: never
    on_failure: never
