variables:
  configuration: Release
  platform: x64

resources:
- repo: self
  fetchDepth: 5

jobs:
- job: Windows_vc141
  pool:
    vmImage: VS2017-Win2016

  variables:
    compiler: vc141
    combination: 'win-$(compiler)-$(platform)-$(configuration)'
    buildFolder: 'build/ninja-$(combination)'
    installCommand: 'choco install ninja'
    artifactBinaries: |
      bin/AlimerPlayer.exe
  steps:
  - template: script/azure_pipelines/build.yml